#!/bin/sh

# ip setting (static/dhcp)
ip=dhcp
[ -n "${global.ip}" ] && ip=${global.ip}
global.dhcp.vendor_id=barebox-${global.hostname}

# static setup used if ip=static
ipaddr=${global.ipaddr}
netmask=${global.netmask}
gateway=${global.gateway}

# MAC address if needed
#ethaddr=xx:xx:xx:xx:xx:xx

# put code to discover eth0 (i.e. 'usb') to /env/network/eth0-discover

exit 0
