#!/bin/sh

BOOT=/boot
global.bootm.image=$BOOT/zImage
global.bootm.oftree=$BOOT/socfpga_arria10_plat.dtb
global.linux.debug=1

for item in ${global.bootm.image} ${global.bootm.oftree}; do
    if [ ! -f ${item} ]; then
	echo "************************************************************"
	echo "* ERROR: Required boot item ${item} is missing. Booting aborted."
	echo "************************************************************"
	exit 1
    fi
done

# Annoyingly, we can't just do partuuid=${mmc0.root$bootsource_instance}
if [ $bootsource_instance -eq 0 ]; then partuuid=${mmc0.root0};
elif [ $bootsource_instance -eq 1 ]; then partuuid=${mmc0.root1};
elif [ $bootsource_instance -eq 2 ]; then partuuid=${mmc0.root2};
elif [ $bootsource_instance -eq 3 ]; then partuuid=${mmc0.root3};
else
    echo "Error, no partition selected in bootsource_instance"
    exit 1
fi

global.linux.bootargs.dyn.root="root=PARTUUID=$partuuid rw rootwait"

if [ -z ${global.linux.debug} ]; then
    global linux.bootargs.dyn.logging="quiet loglevel=0"
    global.linux.bootargs.console="console=none"
fi

true
